### ISSUE TITLE
Add naive sandwiching example

### ISSUE THREAD

**Issue by onbjerg** [onbjerg/ethers-flashbots#12]
It could probably go like this:

1) Get pending transactions
2) Filter them for transactions that perform a swap by checking the 4bytes
3) Attempt to parse swap parameters
4) Construct front and back transactions within parameters
5) Construct the bundle
6) Simulate and submit the bundle

To simplify things a bit, we can just bribe the miner using gas prices instead of using `coinbase.transfer`.

**Comment by avocadochicken** [comment]
Please let this be like a library we can build code on top of. If you want more examples you could merge https://github.com/avocadochicken/ethers-flashbots/blob/master/examples/bribe.rs.
I can add other examples if you like. Lets talk.
Examples should stay like "examples". Easily digestible short code. I am against such (complex) example here.

**Comment by onbjerg** [comment]
Fair enough!
