### ISSUE TITLE
Unable to add git = "https://github.com/onbjerg/ethers-flashbots to cargo.toml

### ISSUE THREAD

**Issue by ChainsightLabs** [onbjerg/ethers-flashbots#24]
error: failed to run custom build command for sha2-asm v0.6.2

i think its because i'm running windows..

found this in ethers-rs and it seems related, wonder if ethers-flashbots need similar fix
https://github.com/gakonst/ethers-rs/pull/679/files

**Comment by onbjerg** [comment]
This is a bug in the ethers dependency that was fixed in the PR you referenced, but (to my knowledge) the fix has not been published on crates.io, so I can't really do much until then :(

**Comment by onbjerg** [comment]
Just following up again here. Perhaps [`[patch.crates-io]`](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) could work out for you?
