### ISSUE TITLE
Errors with the advanced example

### ISSUE THREAD

**Issue by samlaf** [onbjerg/ethers-flashbots#28]
When I run the advanced example with a real funded wallet,
the call to simulate (`client.inner().simulate_bundle(&bundle).await?;`) returns `Error: Some parameters were missing`.

The first thing that `simulate_bundle` runs is
```
bundle
            .block()
            .and(bundle.simulation_block())
            .and(bundle.simulation_timestamp())
            .ok_or(FlashbotsMiddlewareError::MissingParameters)?;
```
so I added a simulation_block and simulation_timestamp to the bundle:
```
    let bundle = BundleRequest::new()
        .push_transaction(tx.rlp_signed(client.signer().chain_id(), &signature))
        .set_block(block_number + 1)
        // these next 2 lines are new
        .set_simulation_block(block_number + 1)
        .set_simulation_timestamp(0);
```
And testing on goerli (https://relay-goerli.flashbots.net) I still get an error which I don't understand:
```
Error: (code: -32000, message: header not found, data: None)
```

**Comment by onbjerg** [comment]
You're asking it to simulate using state from a block that does not exist, assuming `block_number` is the latest block

**Comment by samlaf** [comment]
Not sure why you're closing this. Don't you think the examples should be runnable...?
The point of examples is to help newbies like me learn about your library (and often, as in my case, about flashbots at the same time).

I didn't understand simulation, but I now understand that what I was trying to do doesn't make sense. Nonetheless, I still think you should fix your example so that newbies can learn from it. Otherwise what's the point of having it there?

**Comment by onbjerg** [comment]
I've fixed the example on master now: https://github.com/onbjerg/ethers-flashbots/commit/dc56e21973af419a3ee8ab61292476724462962a
