### ISSUE TITLE
eth_estimateGasBundle 

### ISSUE THREAD

**Issue by thibc81** [onbjerg/ethers-flashbots#34]
Hi,

I think it could be useful to include a method wrapping mev-geth's eth_estimateGasBundle endoint.

Thanks!

**Comment by onbjerg** [comment]
Does not seem to be exposed in the relay, so not currently something this library can handle gracefully. I have some notes on a version 1 of this library that decouples a bit from ethers-rs and adds a bunch of new stuff, but I don't currently have the bandwidth to execute on it. Will look into adding this once the Flashbots relay also supports it (https://github.com/flashbots/mev-relay-js/issues/67)

**Comment by chikko80** [comment]
@onbjerg Would still be nice to have, wouldn't it? Planning to implement eth_estimateGasBundle what do yo think?
