### ISSUE TITLE
Misleading bundle inclusion

### ISSUE THREAD

**Issue by sebastiantf** [onbjerg/ethers-flashbots#47]
https://github.com/onbjerg/ethers-flashbots/blob/d7580fa65b695899ccea3e5db92a131abafc9708/src/pending_bundle.rs#L102-L107

I think this logic of checking only the first transaction was included, is a bit flawed, because there may have been a competing bundle that landed in the same target block with the same first transaction that was being backrun.

Thus it would think the submitted bundle was included, while it was actually a competing bundle with the same specs was the one that got included

**Comment by chikko80** [comment]
Experienced the exact same issue, that's a major problem tbh, especially if you have dependencies/post-actions on the inclusion status
