### ISSUE TITLE
Error simulating tx with ethers-rs 2.0

### ISSUE THREAD

**Issue by ibhagwan** [onbjerg/ethers-flashbots#56]
Using the latest version `0.13.1` with the latest ethers-rs `2.0.6` compiles fine but trying to simulate a tx results in an error from the flashbots relay:
```
    source: RelayError(
        ClientError {
            text: "{\"error\":\"unable to decode txs\"}",
        },
    ),
```

**Comment by ibhagwan** [comment]
~~FYI, upgrading all packages within the `Cargo.toml` seems to solve this issue (used my own fork https://github.com/onbjerg/ethers-flashbots/compare/master...ibhagwan:ethers-flashbots:master), I’ll do some more testing and isolate the problematic package, my first hunch is ethers-rs needs to be upgrade to `2.0.6` (from `2.0.0`).~~

I spoke too early, the issue seems to persist even after the upgrade.

**Comment by onbjerg** [comment]
Can you provide a snippet of your code please?

**Comment by ibhagwan** [comment]
> Can you provide a snippet of your code please?

I can’t post the exact code as it’s part of a non public MEV bot code, I’ll try to generate a minimal snippet and post it here.

**Comment by ibhagwan** [comment]
Actually I spoke too early, the issue seems to persist even after the upgrade, I'll try to to reproduce with a minimal code sample and update this post.

**Comment by ibhagwan** [comment]
This issue can be closed, this isn't a bug in this library, most likely not even in `ethers-rs`.

What actually happened: when upgrading to ethers-rs `2.0` I decided to also upgrade my tx suscription stream and subscribe to my besu node using `newPendingTransactions`  with `includeTransactions: true` (as besu doesn't yet support the geth compatible form as described [here](https://github.com/NethermindEth/nethermind/pull/5299)).

However, using the extended subscription form resulted with transactions  missing the `transaction_type` field  (`transaction_type = None`), that made it so that calling `tx.rlp()` (on transactions I wished to bundle) returned bytes in format that the flashbots relay refused to understand and thus failng with the error `unable to decode txs`.

**Comment by ibhagwan** [comment]
FYI, this is indeed a besu bug, ref: https://github.com/hyperledger/besu/issues/5615
