### ISSUE TITLE
Simulation problem

### ISSUE THREAD

**Issue by DaddyGG** [onbjerg/ethers-flashbots#75]
Hi everyone, 

I was performing test on the Goerli testnet and everything was going fine. I was able to create different transactions (TypedTransaction) using Eip1559TransactionRequest and include them in a bundle, simulate it and send it. Everything was going fine.

Now here is the problem, i decided to go live on the mainnet, i use my own node and when i simulate the transaction the gas price simulated of the tx inside the bundle is not the same as the one i put during the creation of the transaction itself. The problem is only when i am on the mainnet and even if i use a public node i have the same problem.

Has anyone already experienced this? Could it be a serialization problem? 

Thank you in advance for your help and have a good day !

**Comment by DaddyGG** [comment]
Also, when i want to broadcast the bundle to multiple builders, i cannot place all builders in the example.

If i place the  "https://rsync-builder.xyz", builder, i got the error : An error occurred: Deserialization error: data did not match any variant of untagged enum ResponseData at line 1 column 38. Response: {"jsonrpc":"2.0","id":1,"result":null}


For other builders like "https://relay.flashbots.net" or "https://rpc.beaverbuild.org" or even "https://rpc.titanbuilder.xyz/" there is no problem

Maybe this has a link but not sure

**Comment by zerosnacks** [comment]
Possibly related: https://github.com/onbjerg/ethers-flashbots/pull/76
